### ISSUE TITLE
GBD Catalog - error when exporting 0 items

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect#10]
To recreate:
1. Open QGIS
2. Click the GBD widget
3. Click "Export" without any items in results

Results:
Python error message
![image](https://cloud.githubusercontent.com/assets/12919941/11790474/09f8f424-a26a-11e5-8f36-c7c77d5d2a91.png)

**Comment by christyberman** [comment]
The fix is to throw up a UI error to tell the user that there is no data to export. Works both with and without drawing an aoi first.
