### ISSUE TITLE
GBD Catalog - Status filter error

### ISSUE THREAD

**Issue by eong93** [DigitalGlobe/DGConnect#11]
To recreate:
1. Open QGIS
2. Click GBD widget
3. Select "Status" as a filter option
4. Check 1 or 2 of the 3 status boxes

Result:
Python error message
![image](https://cloud.githubusercontent.com/assets/12919941/11791003/ceb960bc-a26c-11e5-83c8-7a49ab7fb9d0.png)

**Comment by wittmer85** [comment]
I've reproduced the bug.  Currently working on it

**Comment by christyberman** [comment]
Filtering on status now works as the only filter as well as combined with other filters.
